mod 'boxen', '2.1.0', :github_tarball => 'boxen/puppet-boxen'
mod 'stdlib', '4.0.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
mod 'repository', '2.3.0', :github_tarball => "boxen/puppet-repository"